from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ablation.complexity import compare_with_full


CASE_ORDER = [
    "full",
    "abs_diff",
    "no_context",
    "concat_decoder",
    "no_boundary",
    "no_deep_supervision",
    "boundary_05",
    "loss_weights_080604",
    "c45_diff_absconcat",
    "c45_context_triple",
]

A0_A7_CASES = [
    "full",
    "abs_diff",
    "no_context",
    "concat_decoder",
    "no_boundary",
    "no_deep_supervision",
    "boundary_05",
    "loss_weights_080604",
]

CASE_META = {
    "full": {
        "code": "A0",
        "label_cn": "完整 LiteCDNet",
        "setting_cn": "完整模型基线",
        "group": "ablation",
        "focus_cn": "统一对照基线",
    },
    "abs_diff": {
        "code": "A1",
        "label_cn": "固定绝对差分替代 DiffFusion",
        "setting_cn": "abs_diff 替换 DiffFusion",
        "group": "ablation",
        "focus_cn": "验证可学习差分融合",
    },
    "no_context": {
        "code": "A2",
        "label_cn": "去除 LiteContextModule",
        "setting_cn": "去 LiteContext",
        "group": "ablation",
        "focus_cn": "验证上下文增强贡献",
    },
    "concat_decoder": {
        "code": "A3",
        "label_cn": "拼接式解码替代加法解码",
        "setting_cn": "concat 解码",
        "group": "ablation",
        "focus_cn": "验证解码效率-精度折中",
    },
    "no_boundary": {
        "code": "A4",
        "label_cn": "去除边界损失",
        "setting_cn": "无 boundary loss",
        "group": "ablation",
        "focus_cn": "验证边界约束贡献",
    },
    "no_deep_supervision": {
        "code": "A5",
        "label_cn": "去除深监督",
        "setting_cn": "无 deep supervision",
        "group": "ablation",
        "focus_cn": "验证深监督贡献",
    },
    "boundary_05": {
        "code": "A6",
        "label_cn": "边界权重调为 0.5",
        "setting_cn": "boundary=0.5",
        "group": "ablation",
        "focus_cn": "验证边界权重敏感性",
    },
    "loss_weights_080604": {
        "code": "A7",
        "label_cn": "多尺度监督权重改为 1.0/0.8/0.6/0.4",
        "setting_cn": "loss weight 调整",
        "group": "ablation",
        "focus_cn": "验证多尺度监督权重",
    },
    "c45_diff_absconcat": {
        "code": "E1",
        "label_cn": "仅增强 C4/C5 差分融合",
        "setting_cn": "增强 C4/C5 差分融合",
        "group": "enhancement",
        "focus_cn": "高层定点增强",
    },
    "c45_context_triple": {
        "code": "E2",
        "label_cn": "仅增强 C4/C5 三分支上下文",
        "setting_cn": "增强 C4/C5 三分支上下文",
        "group": "enhancement",
        "focus_cn": "高层定点增强",
    },
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate thesis-ready ablation presentation tables and prose.")
    parser.add_argument("--summary_csv", type=str, default="", help="Path to summary.csv generated by main_ablation_suite.py")
    parser.add_argument("--suite_name", type=str, default="", help="Suite name under ablation_reports/")
    parser.add_argument("--report_root", type=str, default="ablation_reports", help="Root directory of ablation reports")
    parser.add_argument("--curve_summary_csv", type=str, default="", help="Optional curve summary csv path")
    parser.add_argument("--complexity_json", type=str, default="", help="Optional complexity json path")
    parser.add_argument("--output_dir", type=str, default="", help="Optional custom output directory")
    return parser


def parse_float(value: str | int | float | None) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def fmt_float(value: object, digits: int = 2) -> str:
    if not isinstance(value, (int, float)):
        return "-"
    return f"{float(value):.{digits}f}"


def fmt_metric(value: object, digits: int = 5) -> str:
    if not isinstance(value, (int, float)):
        return "-"
    return f"{float(value):.{digits}f}"


def fmt_delta(value: object, digits: int = 5) -> str:
    if not isinstance(value, (int, float)):
        return "-"
    if abs(float(value)) < 0.5 * 10 ** (-digits):
        return "0.00000"
    return f"{float(value):+.{digits}f}"


def resolve_summary_csv(args: argparse.Namespace) -> Path | None:
    if args.summary_csv:
        return Path(args.summary_csv).resolve()
    if args.suite_name:
        return (PROJECT_ROOT / args.report_root / args.suite_name / "summary.csv").resolve()
    return None


def resolve_curve_summary_csv(args: argparse.Namespace) -> Path:
    if args.curve_summary_csv:
        return Path(args.curve_summary_csv).resolve()
    return (PROJECT_ROOT / "论文插图素材" / "_derived_metadata" / "曲线图_A0-A7" / "curve_summary.csv").resolve()


def resolve_complexity_json(args: argparse.Namespace) -> Path:
    if args.complexity_json:
        return Path(args.complexity_json).resolve()
    return (PROJECT_ROOT / "论文插图素材" / "_derived_metadata" / "复杂度图_A0-A7" / "all_cases_complexity.json").resolve()


def load_rows_from_summary(summary_csv: Path) -> dict[str, dict[str, object]]:
    rows_by_case: dict[str, dict[str, object]] = {}
    with summary_csv.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            case = str(row.get("case", "")).strip()
            if not case:
                continue
            parsed: dict[str, object] = dict(row)
            for key in (
                "acc",
                "delta_acc_vs_full",
                "miou",
                "delta_miou_vs_full",
                "mf1",
                "delta_mf1_vs_full",
                "precision_1",
                "recall_1",
                "elapsed_sec",
                "elapsed_min",
                "params_m",
                "flops_g",
            ):
                parsed[key] = parse_float(row.get(key))
            rows_by_case[case] = parsed
    return rows_by_case


def load_rows_from_curve_summary(curve_summary_csv: Path) -> dict[str, dict[str, object]]:
    rows_by_case: dict[str, dict[str, object]] = {}
    with curve_summary_csv.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            case_name = str(row.get("case_name", "")).strip()
            case = {
                "full": "full",
                "abs_diff": "abs_diff",
                "no_context": "no_context",
                "concat_decoder": "concat_decoder",
                "no_boundary": "no_boundary",
                "no_deep_supervision": "no_deep_supervision",
                "boundary_05": "boundary_05",
                "loss_weights_080604": "loss_weights_080604",
            }.get(case_name)
            if not case:
                continue
            parsed: dict[str, object] = {
                "case": case,
                "status": row.get("status", ""),
                "last_epoch": parse_float(row.get("last_epoch")),
                "max_epoch": parse_float(row.get("max_epoch")),
                "best_epoch": parse_float(row.get("best_epoch")),
                "miou": parse_float(row.get("best_val_miou")),
                "mf1": parse_float(row.get("best_val_mf1")),
                "acc": parse_float(row.get("best_val_acc")),
                "miou_last": parse_float(row.get("last_val_miou")),
                "mf1_last": parse_float(row.get("last_val_mf1")),
                "acc_last": parse_float(row.get("last_val_acc")),
            }
            rows_by_case[case] = parsed
    return rows_by_case


def load_complexity_rows(complexity_json: Path) -> dict[str, dict[str, object]]:
    data = json.loads(complexity_json.read_text(encoding="utf-8-sig"))
    return {str(row["case"]): dict(row) for row in data}


def merge_rows(args: argparse.Namespace) -> list[dict[str, object]]:
    summary_csv = resolve_summary_csv(args)
    if summary_csv and summary_csv.exists():
        perf_rows = load_rows_from_summary(summary_csv)
    else:
        curve_summary_csv = resolve_curve_summary_csv(args)
        if not curve_summary_csv.exists():
            raise FileNotFoundError(f"curve summary csv not found: {curve_summary_csv}")
        perf_rows = load_rows_from_curve_summary(curve_summary_csv)

    complexity_json = resolve_complexity_json(args)
    if not complexity_json.exists():
        raise FileNotFoundError(f"complexity json not found: {complexity_json}")
    complexity_rows = load_complexity_rows(complexity_json)

    merged_rows: list[dict[str, object]] = []
    baseline_miou = parse_float(perf_rows.get("full", {}).get("miou"))
    baseline_mf1 = parse_float(perf_rows.get("full", {}).get("mf1"))

    for case in CASE_ORDER:
        meta = CASE_META[case]
        perf = dict(perf_rows.get(case, {}))
        complexity = dict(complexity_rows.get(case, {}))

        row: dict[str, object] = {
            "case": case,
            "code": meta["code"],
            "label_cn": meta["label_cn"],
            "setting_cn": meta["setting_cn"],
            "focus_cn": meta["focus_cn"],
            "group": meta["group"],
            "status": perf.get("status", "missing"),
            "best_epoch": perf.get("best_epoch"),
            "last_epoch": perf.get("last_epoch"),
            "max_epoch": perf.get("max_epoch"),
            "miou": parse_float(perf.get("miou")),
            "mf1": parse_float(perf.get("mf1")),
            "acc": parse_float(perf.get("acc")),
            "params_m": parse_float(complexity.get("params_m")),
            "flops_g": parse_float(complexity.get("flops_g")),
            "delta_params_m_vs_full": parse_float(complexity.get("delta_params_m_vs_full")),
            "delta_flops_g_vs_full": parse_float(complexity.get("delta_flops_g_vs_full")),
        }
        row["delta_miou_vs_full"] = (
            None if row["miou"] is None or baseline_miou is None else float(row["miou"]) - baseline_miou
        )
        row["delta_mf1_vs_full"] = (
            None if row["mf1"] is None or baseline_mf1 is None else float(row["mf1"]) - baseline_mf1
        )

        if row["params_m"] is None or row["flops_g"] is None:
            complexity_fallback = compare_with_full(case)
            row["params_m"] = complexity_fallback["params_m"]
            row["flops_g"] = complexity_fallback["flops_g"]
            row["delta_params_m_vs_full"] = complexity_fallback["delta_params_m_vs_full"]
            row["delta_flops_g_vs_full"] = complexity_fallback["delta_flops_g_vs_full"]

        merged_rows.append(row)

    return merged_rows


def build_core_ablation_table(rows: list[dict[str, object]]) -> str:
    core_rows = [row for row in rows if row["case"] in A0_A7_CASES]
    lines = [
        "# 表4-4 LiteCDNet 标准消融结果总表",
        "",
        "| 编号 | 设置 | Params(M) | ΔParams | FLOPs(G) | ΔFLOPs | mIoU | mF1 | ΔmIoU | 备注 |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in core_rows:
        remark = "基线" if row["case"] == "full" else (
            f"best@epoch {int(row['best_epoch'])}" if isinstance(row.get("best_epoch"), (int, float)) else str(row.get("status", "-"))
        )
        if row.get("status") == "in_progress" and isinstance(row.get("best_epoch"), (int, float)):
            remark = f"进行中，当前 best@epoch {int(row['best_epoch'])}"
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row["code"]),
                    str(row["setting_cn"]),
                    fmt_float(row.get("params_m")),
                    "—" if row["case"] == "full" else fmt_delta(row.get("delta_params_m_vs_full")),
                    fmt_float(row.get("flops_g")),
                    "—" if row["case"] == "full" else fmt_delta(row.get("delta_flops_g_vs_full")),
                    fmt_metric(row.get("miou")),
                    fmt_metric(row.get("mf1")),
                    "—" if row["case"] == "full" else fmt_delta(row.get("delta_miou_vs_full")),
                    remark,
                ]
            )
            + " |"
        )
    lines.append("")
    lines.append("注：A0 作为完整 LiteCDNet 基线；A1-A7 为标准消融与训练策略组；ΔParams = 当前 Params - A0 Params；ΔFLOPs = 当前 FLOPs - A0 FLOPs；ΔmIoU = 当前 mIoU - A0 mIoU。")
    return "\n".join(lines) + "\n"


def build_enhancement_note(rows: list[dict[str, object]]) -> str:
    enhancement_rows = [row for row in rows if row["group"] == "enhancement"]
    lines = [
        "# E1-E2 口径说明",
        "",
        "E1-E2 属于高层定点增强组，不与 A0-A7 混在同一张标准消融总表中。",
        "当前若未完成正式训练结果，应仅纳入复杂度和结构扩展分析，不纳入正式性能曲线与核心消融结论。",
        "",
        "| 编号 | 设置 | Params(M) | FLOPs(G) | 当前状态 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in enhancement_rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row["code"]),
                    str(row["setting_cn"]),
                    fmt_float(row.get("params_m")),
                    fmt_float(row.get("flops_g")),
                    str(row.get("status", "未纳入正式性能表")),
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def build_module_analysis(rows: list[dict[str, object]]) -> str:
    rows_by_case = {str(row["case"]): row for row in rows}

    def p(case: str) -> dict[str, object]:
        return rows_by_case[case]

    def miou_drop_text(case: str) -> str:
        value = p(case).get("delta_miou_vs_full")
        if not isinstance(value, (int, float)):
            return "变化暂缺"
        return f"{value:+.5f}"

    lines = [
        "# 4.4 消融实验与模块贡献分析",
        "",
        "口径说明：本节 A0-A7 统一采用同一套消融统计口径，其中 A0 固定对应 `checkpoints/LEVIR_LiteCDNet_BCEDiceBoundary0.3_AdamW_Cosine_150` 这一完整模型基线；表中 mIoU 与 mF1 来自该实验体系下的 best val 记录，而不是 4.3 主结果中的单独测试口径。",
        "",
        "## 4.4.1 总消融表",
        "",
        "本节建议先给出一张 A0-A7 的统一结果总表，核心列至少包括：编号、设置、Params、FLOPs、mIoU、mF1 与 ΔmIoU。",
        "其中 ΔmIoU 统一定义为“当前设置 mIoU - A0 基线 mIoU”，用于直接反映每个模块或训练策略的净贡献。",
        "",
        "## 4.4.2 分模块结果归因",
        "",
        f"1. DiffFusion（A1）",
        f"将 DiffFusion 替换为固定绝对差分后，mIoU 相对 A0 {miou_drop_text('abs_diff')}。这说明固定差分虽然能够直接强化变化响应，但缺乏对双时相语义信息的保留能力，容易放大伪变化区域。相比之下，DiffFusion 通过可学习融合，在抑制噪声差异的同时保留互补语义信息，因此更有利于提升变化区域判别能力。",
        "",
        f"2. LiteContext（A2）",
        f"去除 LiteContext 后，mIoU 相对 A0 {miou_drop_text('no_context')}。这一结果说明单尺度局部卷积提供的感受野仍然有限，在复杂背景下更容易产生误检。LiteContext 通过局部分支与膨胀分支协同，在较低开销下引入多尺度上下文，有助于提升变化区域的整体一致性。",
        "",
        f"3. 解码方式（A3）",
        f"将加法式解码替换为 concat 解码后，mIoU 相对 A0 {miou_drop_text('concat_decoder')}，但 Params 与 FLOPs 明显上升。该结果表明，concat 的确能提供更丰富的特征表达，但也会导致通道膨胀，使轻量化优势减弱。因而加法式解码更符合 LiteCDNet 面向轻量部署的效率-精度折中目标。",
        "",
        f"4. Boundary Loss（A4 / A6）",
        f"A4 去除边界损失后，mIoU 相对 A0 {miou_drop_text('no_boundary')}，说明区域级损失对细粒度边界的约束仍然不足。A6 将边界权重调为 0.5 后，mIoU 相对 A0 {miou_drop_text('boundary_05')}，反映出边界分支存在权重敏感性，但并非权重越大越优，仍需与主体区域监督保持平衡。",
        "",
        f"5. Deep Supervision（A5）",
        f"去除深监督后，mIoU 相对 A0 {miou_drop_text('no_deep_supervision')}。这说明中间层的直接优化信号对轻量模型仍然重要，深监督有助于改善训练稳定性，并提升最终收敛效果。",
        "",
        f"6. 多尺度监督权重（A7）",
        f"A7 将监督权重调整为 1.0/0.8/0.6/0.4 后，mIoU 相对 A0 {miou_drop_text('loss_weights_080604')}。从当前结果看，这组调整更接近训练策略层面的细化优化，用于验证多尺度输出之间的权重分配是否会影响最终性能上限。",
        "",
        "## 4.4.3 总结段",
        "",
        "综合消融结果可以看出，LiteCDNet 的性能提升并不依赖单一模块，而是多个轻量组件协同作用的结果。",
        "其中，DiffFusion 主要提升差异表达的可学习性，LiteContext 提供多尺度上下文支持，加法式解码控制模型复杂度，而边界损失与深监督则共同提升训练稳定性与边界质量。",
        "这意味着本文的贡献重点并不在于某一个重型模块本身，而在于围绕轻量变化检测目标所构建的整体替代路径与协同设计。",
        "",
        "## 4.4.4 呈现建议",
        "",
        "正文建议采用“总表先行、模块解释跟进、总结段收束”的三层结构。",
        "如果需要再加一张图，优先选择 A0-A7 的 mIoU 柱状对比图，用于直观呈现各设置相对 A0 的升降幅度。",
    ]
    return "\n".join(lines) + "\n"


def build_caption_notes() -> str:
    return (
        "表题建议：表4-4 LiteCDNet 标准消融结果总表\n"
        "表注建议：A0 为完整 LiteCDNet 基线，固定对应 checkpoints/LEVIR_LiteCDNet_BCEDiceBoundary0.3_AdamW_Cosine_150；A1-A7 为标准消融与训练策略组，ΔParams = 当前 Params - A0 Params，ΔFLOPs = 当前 FLOPs - A0 FLOPs，ΔmIoU = 当前 mIoU - A0 mIoU。\n"
        "正文引句建议：为系统验证 LiteCDNet 各关键模块与训练策略的实际贡献，本文在统一训练设置下构建了 A0-A7 标准消融组，其中 A0 固定采用 checkpoints 中的 boundary0.3 完整模型作为统一对照，并从精度、参数量与计算量三个维度同步进行对比分析，结果如表4-4所示。\n"
        "图题建议：图4-X 不同消融设置下 mIoU 对比柱状图。\n"
    )


def build_source_note() -> str:
    return (
        "# A0 统一口径说明\n\n"
        "当前 4.4 消融表的 A0 统一对应：\n\n"
        "- `checkpoints/LEVIR_LiteCDNet_BCEDiceBoundary0.3_AdamW_Cosine_150`\n\n"
        "也就是说，A0 不再引用 4.3 中单独拿出来表述的那套主测试结果口径，而是与 A1-A7 一样，统一放在同一套消融比较框架下。\n\n"
        "建议写法：\n\n"
        "- 4.3 保留为“主模型与 SEIFNet 对比结果”\n"
        "- 4.4 保留为“A0-A7 标准消融结果”\n"
        "- 两节不要混用同一列数值\n\n"
        "如果后续希望进一步完全统一，也应当把 A1-A7 一起切换到同一套测试口径，而不是只单独替换 A0。\n"
    )


def set_plot_style() -> None:
    matplotlib.use("Agg")
    matplotlib.rcParams["font.sans-serif"] = ["Microsoft YaHei", "SimHei", "Arial Unicode MS", "DejaVu Sans"]
    matplotlib.rcParams["axes.unicode_minus"] = False
    matplotlib.rcParams["figure.dpi"] = 150
    matplotlib.rcParams["savefig.dpi"] = 240


def create_miou_bar_chart(rows: list[dict[str, object]], output_path: Path) -> None:
    set_plot_style()
    core_rows = [row for row in rows if row["case"] in A0_A7_CASES]
    codes = [str(row["code"]) for row in core_rows]
    values = [float(row["miou"]) for row in core_rows]
    deltas = [row.get("delta_miou_vs_full") for row in core_rows]

    fig, ax = plt.subplots(figsize=(11.5, 5.8), facecolor="#faf8f4")
    colors = []
    for idx, delta in enumerate(deltas):
        if idx == 0:
            colors.append("#4f6d7a")
        elif isinstance(delta, (int, float)) and delta >= 0:
            colors.append("#2a9d8f")
        else:
            colors.append("#d97732")

    bars = ax.bar(codes, values, color=colors, width=0.68)
    ymin = min(values) - 0.01
    ymax = max(values) + 0.012
    ax.set_ylim(ymin, ymax)
    ax.set_ylabel("mIoU")
    ax.set_title("A0-A7 mIoU Comparison", fontsize=14, fontweight="bold")
    ax.grid(axis="y", linestyle="--", alpha=0.25)

    for bar, row in zip(bars, core_rows):
        value = float(row["miou"])
        delta = row.get("delta_miou_vs_full")
        label = f"{value:.5f}"
        if row["case"] != "full" and isinstance(delta, (int, float)):
            label += f"\n({delta:+.5f})"
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            value + 0.0005,
            label,
            ha="center",
            va="bottom",
            fontsize=9,
        )

    a7_row = next((row for row in core_rows if row["case"] == "loss_weights_080604"), None)
    if a7_row and a7_row.get("status") == "completed":
        note_text = "注：括号内为 ΔmIoU = 当前 mIoU - A0 mIoU。A7 已完成全部训练轮次，柱高取其 best mIoU。"
    else:
        note_text = "注：括号内为 ΔmIoU = 当前 mIoU - A0 mIoU。A7 当前为进行中实验，柱高取当前 best mIoU。"

    fig.text(0.5, 0.02, note_text, ha="center", fontsize=10)
    plt.tight_layout(rect=(0.02, 0.06, 0.98, 0.95))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, bbox_inches="tight")
    plt.close(fig)


def build_chart_note(rows: list[dict[str, object]]) -> str:
    a7_row = next((row for row in rows if row["case"] == "loss_weights_080604"), None)
    if a7_row and a7_row.get("status") == "completed":
        a7_note = "A7 已完成全部训练轮次，因此图中使用其完整训练过程中的 best mIoU。"
    else:
        a7_note = "A7 当前尚未跑满 149 轮，因此图中取其当前 best mIoU，而不是最终收敛值。"
    return (
        "# 图4-X 说明\n\n"
        "图4-X 为 A0-A7 不同消融设置下的 mIoU 对比柱状图。\n"
        "图中柱高对应各实验组的 mIoU，括号内标注为相对 A0 的 ΔmIoU。\n"
        f"{a7_note}\n"
    )


def save_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8-sig")


def main() -> None:
    args = build_parser().parse_args()
    rows = merge_rows(args)

    default_output = PROJECT_ROOT / "论文插图素材" / "_derived_metadata" / "表格与分析_A0-A7"
    output_dir = Path(args.output_dir).resolve() if args.output_dir else default_output.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    figure_dir = (PROJECT_ROOT / "论文插图素材" / "可直接使用图_20260422" / "曲线图_A0-A7").resolve()
    figure_dir.mkdir(parents=True, exist_ok=True)
    figure_path = figure_dir / "fig4-x_ablation_miou_bar_A0_A7.png"

    files_and_contents = [
        (output_dir / "table_4_4_core_ablation_A0_A7.md", build_core_ablation_table(rows)),
        (output_dir / "table_4_4_core_ablation_A0_A7_word.txt", build_core_ablation_table(rows)),
        (output_dir / "section_4_4_module_contribution_analysis.md", build_module_analysis(rows)),
        (output_dir / "E1_E2_scope_note.md", build_enhancement_note(rows)),
        (output_dir / "A0_source_scope_note.md", build_source_note()),
        (output_dir / "table_caption_and_reference_notes.txt", build_caption_notes()),
        (output_dir / "fig4_x_ablation_miou_bar_note.md", build_chart_note(rows)),
    ]

    for path, content in files_and_contents:
        save_text(path, content)
    create_miou_bar_chart(rows, figure_path)

    print(f"output_dir: {output_dir}")
    print(f"figure_path: {figure_path}")
    print(f"generated_at: {datetime.now().isoformat(timespec='seconds')}")
    print("generated_files:")
    for path, _ in files_and_contents:
        print(f"- {path}")
    print(f"- {figure_path}")


if __name__ == "__main__":
    main()
