from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt

from ablation.complexity import compare_with_full


PROJECT_ROOT = Path(__file__).resolve().parents[2]
CASE_ORDER = [
    "full",
    "abs_diff",
    "no_context",
    "concat_decoder",
    "no_boundary",
    "no_deep_supervision",
    "boundary_05",
    "loss_weights_080604",
    "c45_diff_absconcat",
    "c45_context_triple",
]
CASE_META = {
    "full": {"code": "A0", "label_cn": "完整 LiteCDNet", "label_short": "A0 Full"},
    "abs_diff": {"code": "A1", "label_cn": "固定绝对差分", "label_short": "A1 AbsDiff"},
    "no_context": {"code": "A2", "label_cn": "去除 LiteContext", "label_short": "A2 w/o Context"},
    "concat_decoder": {"code": "A3", "label_cn": "拼接式解码", "label_short": "A3 ConcatDec"},
    "no_boundary": {"code": "A4", "label_cn": "去除边界损失", "label_short": "A4 w/o Boundary"},
    "no_deep_supervision": {"code": "A5", "label_cn": "去除深监督", "label_short": "A5 w/o DeepSup"},
    "boundary_05": {"code": "A6", "label_cn": "边界权重=0.5", "label_short": "A6 Boundary0.5"},
    "loss_weights_080604": {"code": "A7", "label_cn": "监督权重=1.0/0.8/0.6/0.4", "label_short": "A7 LossW"},
    "c45_diff_absconcat": {"code": "E1", "label_cn": "增强 C4/C5 差分融合", "label_short": "E1 C45 Diff+"},
    "c45_context_triple": {"code": "E2", "label_cn": "增强 C4/C5 三分支上下文", "label_short": "E2 C45 Ctx3"},
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate an ablation overview figure with metrics and complexity statistics.")
    parser.add_argument("--summary_csv", type=str, default="", help="Path to summary.csv generated by main_ablation_suite.py")
    parser.add_argument("--suite_name", type=str, default="", help="Suite name under ablation_reports/")
    parser.add_argument("--report_root", type=str, default="ablation_reports", help="Ablation report root directory")
    parser.add_argument("--output_dir", type=str, default="", help="Optional custom output directory")
    parser.add_argument("--img_size", type=int, default=256, help="Input image size for complexity profiling")
    parser.add_argument("--n_class", type=int, default=2, help="Number of output classes")
    return parser


def resolve_summary_csv(args: argparse.Namespace) -> Path:
    if args.summary_csv:
        return Path(args.summary_csv).resolve()
    if not args.suite_name:
        raise ValueError("Please provide --summary_csv or --suite_name.")
    return (PROJECT_ROOT / args.report_root / args.suite_name / "summary.csv").resolve()


def parse_float(value: str | None) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def load_summary_rows(summary_csv: Path) -> dict[str, dict[str, object]]:
    rows_by_case: dict[str, dict[str, object]] = {}
    with summary_csv.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            case = str(row.get("case", "")).strip()
            if not case:
                continue
            rows_by_case[case] = {
                "case": case,
                "status": row.get("status", ""),
                "miou": parse_float(row.get("miou")),
                "mf1": parse_float(row.get("mf1")),
                "acc": parse_float(row.get("acc")),
                "precision_1": parse_float(row.get("precision_1")),
                "recall_1": parse_float(row.get("recall_1")),
                "delta_miou_vs_full": parse_float(row.get("delta_miou_vs_full")),
                "delta_mf1_vs_full": parse_float(row.get("delta_mf1_vs_full")),
            }
    return rows_by_case


def build_combined_rows(summary_rows: dict[str, dict[str, object]], img_size: int, n_class: int) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for case in CASE_ORDER:
        meta = CASE_META[case]
        metrics = summary_rows.get(case, {})
        complexity = compare_with_full(case, img_size=img_size, n_class=n_class)
        rows.append(
            {
                "case": case,
                "code": meta["code"],
                "label_cn": meta["label_cn"],
                "label_short": meta["label_short"],
                "miou": metrics.get("miou"),
                "mf1": metrics.get("mf1"),
                "acc": metrics.get("acc"),
                "delta_miou_vs_full": metrics.get("delta_miou_vs_full"),
                "delta_mf1_vs_full": metrics.get("delta_mf1_vs_full"),
                "params_m": complexity["params_m"],
                "flops_g": complexity["flops_g"],
            }
        )
    return rows


def write_combined_csv(rows: list[dict[str, object]], output_path: Path) -> None:
    with output_path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_combined_json(rows: list[dict[str, object]], output_path: Path) -> None:
    output_path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")


def safe_percent(value: object) -> float:
    return float(value) * 100 if isinstance(value, (int, float)) else float("nan")


def format_percent_text(value: object) -> str:
    if isinstance(value, (int, float)):
        return f"{float(value) * 100:.2f}%"
    return "待补实验结果"


def format_delta_pp_text(value: object) -> str:
    if isinstance(value, (int, float)):
        return f"{float(value) * 100:+.2f} 个百分点"
    return "待补"


def set_plot_style() -> None:
    matplotlib.rcParams["font.sans-serif"] = ["Microsoft YaHei", "SimHei", "Arial Unicode MS", "DejaVu Sans"]
    matplotlib.rcParams["axes.unicode_minus"] = False


def annotate_bars(ax, bars, fmt: str) -> None:
    for bar in bars:
        height = bar.get_height()
        if height != height:
            continue
        ax.text(bar.get_x() + bar.get_width() / 2, height, fmt.format(height), ha="center", va="bottom", fontsize=8)


def create_overview_figure(rows: list[dict[str, object]], output_path: Path) -> None:
    set_plot_style()
    labels = [row["code"] for row in rows]
    x = list(range(len(rows)))
    miou_vals = [safe_percent(row["miou"]) for row in rows]
    mf1_vals = [safe_percent(row["mf1"]) for row in rows]
    params_vals = [float(row["params_m"]) for row in rows]
    flops_vals = [float(row["flops_g"]) for row in rows]

    fig, axes = plt.subplots(2, 2, figsize=(16, 10))
    fig.patch.set_facecolor("#fbfaf7")

    ax1 = axes[0, 0]
    width = 0.36
    bars1 = ax1.bar([xi - width / 2 for xi in x], miou_vals, width=width, color="#d94841", label="mIoU (%)")
    bars2 = ax1.bar([xi + width / 2 for xi in x], mf1_vals, width=width, color="#2f6c99", label="mF1 (%)")
    ax1.set_title("Performance Comparison", fontsize=12, fontweight="bold")
    ax1.set_xticks(x)
    ax1.set_xticklabels(labels)
    ax1.grid(axis="y", linestyle="--", alpha=0.25)
    ax1.legend(frameon=False)
    annotate_bars(ax1, bars1, "{:.2f}")
    annotate_bars(ax1, bars2, "{:.2f}")

    ax2 = axes[0, 1]
    bars3 = ax2.bar(x, params_vals, width=0.55, color="#6c8f3d")
    ax2.set_xticks(x)
    ax2.set_xticklabels(labels)
    ax2.set_title("Params Comparison", fontsize=12, fontweight="bold")
    ax2.grid(axis="y", linestyle="--", alpha=0.2)
    annotate_bars(ax2, bars3, "{:.2f}")

    ax3 = axes[1, 0]
    bars4 = ax3.bar(x, flops_vals, width=0.55, color="#a05a2c")
    ax3.set_xticks(x)
    ax3.set_xticklabels(labels)
    ax3.set_title("FLOPs Comparison", fontsize=12, fontweight="bold")
    ax3.grid(axis="y", linestyle="--", alpha=0.2)
    annotate_bars(ax3, bars4, "{:.2f}")

    ax4 = axes[1, 1]
    ax4.scatter(params_vals, miou_vals, s=140, color="#6b7280", edgecolors="black", linewidths=0.5)
    for row, px, py in zip(rows, params_vals, miou_vals):
        if py == py:
            ax4.annotate(row["code"], (px, py), xytext=(6, 6), textcoords="offset points", fontsize=9)
    ax4.set_title("Trade-off: Params vs mIoU", fontsize=12, fontweight="bold")
    ax4.set_xlabel("Params (M)")
    ax4.set_ylabel("mIoU (%)")
    ax4.grid(linestyle="--", alpha=0.25)

    fig.suptitle("LiteCDNet Ablation and Enhancement Overview", fontsize=15, fontweight="bold", y=0.98)
    fig.text(
        0.5,
        0.02,
        "A0-A7 denote standard ablations. E1-E2 denote high-level C4/C5 enhancement settings.",
        ha="center",
        fontsize=9,
    )
    plt.tight_layout(rect=(0, 0.04, 1, 0.96))
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def write_notes(rows: list[dict[str, object]], output_path: Path) -> None:
    lines = [
        "图题建议：图4-x LiteCDNet 消融与增强实验综合对比图",
        "正文引用建议：为同时展示 A0-A7 标准消融与 E1-E2 高层增强在精度和复杂度上的变化，本文进一步绘制了综合对比图，如图4-x所示。",
        "使用说明：A0-A7 为标准消融编号，E1-E2 为高层增强编号。",
        "",
        "各配置摘要：",
    ]
    for row in rows:
        lines.append(
            f"{row['code']} {row['label_cn']} | Params={row['params_m']:.2f}M | FLOPs={row['flops_g']:.2f}G | "
            f"mIoU={format_percent_text(row['miou'])} | mF1={format_percent_text(row['mf1'])}"
        )
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8-sig")


def write_bilingual_caption_package(output_path: Path) -> None:
    lines = [
        "中文图题：图4-x LiteCDNet 消融与增强实验综合对比图",
        "English Caption: Figure 4-x Comprehensive comparison of LiteCDNet ablation and enhancement settings",
        "",
        "图注（中文）：A0-A7 表示标准消融实验编号，E1-E2 表示仅在 C4/C5 进行高层定点增强的补充实验编号。",
        "Figure Note (English): A0-A7 denote standard ablation settings, while E1-E2 denote supplementary high-level enhancement settings applied only to C4/C5.",
    ]
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8-sig")


def write_ch4_analysis(rows: list[dict[str, object]], output_path: Path) -> None:
    baseline = next((row for row in rows if row["case"] == "full"), None)
    if baseline is None:
        output_path.write_text("未找到 A0 完整模型结果，暂时无法生成第四章分析文字。\n", encoding="utf-8-sig")
        return

    lines = [
        "第四章可直接粘贴分析文字",
        "",
        f"A0 完整 LiteCDNet 在当前实验设置下取得了 {format_percent_text(baseline.get('miou'))} 的 mIoU 和 {format_percent_text(baseline.get('mf1'))} 的 mF1。",
        "在此基础上，A1-A7 用于验证标准单变量结构或训练权重设置，E1-E2 用于验证高层 C4/C5 定点增强的潜力。",
        "",
    ]
    for row in rows:
        if row["case"] == "full":
            continue
        lines.append(
            f"{row['code']} {row['label_cn']} 的 mIoU 为 {format_percent_text(row.get('miou'))}，相对 A0 变化 {format_delta_pp_text(row.get('delta_miou_vs_full'))}；"
            f"mF1 为 {format_percent_text(row.get('mf1'))}，相对 A0 变化 {format_delta_pp_text(row.get('delta_mf1_vs_full'))}。"
        )
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8-sig")


def main() -> None:
    args = build_parser().parse_args()
    summary_csv = resolve_summary_csv(args)
    if not summary_csv.exists():
        raise FileNotFoundError(f"summary.csv not found: {summary_csv}")

    summary_rows = load_summary_rows(summary_csv)
    output_dir = Path(args.output_dir).resolve() if args.output_dir else (summary_csv.parent / "ablation_overview").resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    combined_rows = build_combined_rows(summary_rows, img_size=args.img_size, n_class=args.n_class)
    files = [
        output_dir / "ablation_overview_metrics.csv",
        output_dir / "ablation_overview_metrics.json",
        output_dir / "ablation_overview_figure.png",
        output_dir / "figure_caption_and_reference_notes.txt",
        output_dir / "figure_caption_bilingual.txt",
        output_dir / "section_4_4_overview_analysis.txt",
    ]

    write_combined_csv(combined_rows, files[0])
    write_combined_json(combined_rows, files[1])
    create_overview_figure(combined_rows, files[2])
    write_notes(combined_rows, files[3])
    write_bilingual_caption_package(files[4])
    write_ch4_analysis(combined_rows, files[5])

    print(f"summary.csv: {summary_csv}")
    print(f"output_dir: {output_dir}")
    print("generated_files:")
    for path in files:
        print(f"- {path}")


if __name__ == "__main__":
    main()
